name: JS Unit Test

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt updates
        run: sudo apt -y update; sudo apt -y upgrade;
      - name: Install prerequisites
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo npm install
      - name: Start local http server
        run: sudo npm run http-server &
      - name: Run tests
        run: sudo npm test
